name: minestation_controller
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
      - family: Rajdhani
        fonts:
          - asset: assets/fonts/Rajdhani-Bold.ttf
            weight: 700
      - family: Inter
        fonts:
          - asset: assets/fonts/Inter_24pt-Regular.ttf
      - family: JetBrainsMono
        fonts:
          - asset: assets/fonts/JetBrainsMono-Regular.ttf